name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Build and Publish
        run: |
          pip install build twine
          # Navigate into the subdirectory to build
          cd python-sdk
          python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Tell the action where the build artifacts are
          packages-dir: python-sdk/dist/